import type {
  Annonce,
  Conversation,
  DocumentItem,
  Entreprise,
  Order,
  User,
} from '$lib/types';

function daysAgo(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
}

function asset(name: string): string {
  return `/demo/${name}`;
}

export interface DemoState {
  loggedIn: boolean;
  currentUserId: string | null;
  users: Record<string, User>;
  entreprises: Record<string, Entreprise>;
  annonces: Record<string, Annonce>;
  orders: Record<string, Order>;
  conversations: Record<string, Conversation>;
  documents: Record<string, DocumentItem>;
}

export const ME_EMAIL = 'demo@vitilink.fr';

export function createSeedState(): DemoState {
  const entreprises: Record<string, Entreprise> = {
    'e-me': {
      id: 'e-me',
      name: 'Domaine des Trois Chênes',
      type: 'EARL',
      status: 'VERIFIED',
      siren: '812345678',
      siret: '81234567800012',
      vatNumber: 'FR12812345678',
      cviNumber: 'CVI213045',
      addressLine1: '14 route des Vignes',
      postalCode: '21190',
      city: 'Meursault',
      country: 'France',
      region: 'Bourgogne',
      department: "Côte-d'Or",
      appellations: ['Meursault', 'Pommard'],
      grapeVarieties: ['Chardonnay', 'Pinot Noir'],
      surfaceHa: 14,
      annualVolume: 65000,
      soughtProducts: ['Merlot', 'Syrah'],
      soughtVolume: '50-200 hl',
      verifiedAt: daysAgo(120),
      documents: [],
      createdAt: daysAgo(400),
      updatedAt: daysAgo(10),
    },
    'e-hauterive': {
      id: 'e-hauterive',
      name: 'Château Haute-Rive',
      type: 'SAS',
      status: 'VERIFIED',
      region: 'Bordeaux',
      city: 'Saint-Émilion',
      country: 'France',
      appellations: ['Saint-Émilion'],
      grapeVarieties: ['Merlot'],
      soughtProducts: [],
      createdAt: daysAgo(500),
    },
    'e-terrasses': {
      id: 'e-terrasses',
      name: 'Clos des Terrasses',
      type: 'GAEC',
      status: 'VERIFIED',
      region: 'Rhône',
      city: 'Tain-l’Hermitage',
      country: 'France',
      appellations: ['Crozes-Hermitage'],
      grapeVarieties: ['Syrah'],
      soughtProducts: [],
      createdAt: daysAgo(300),
    },
    'e-soleil': {
      id: 'e-soleil',
      name: 'Domaine du Soleil Levant',
      type: 'EARL',
      status: 'VERIFIED',
      region: 'Languedoc-Roussillon',
      city: 'Gigondas',
      country: 'France',
      appellations: ['Côtes du Rhône Villages'],
      grapeVarieties: ['Grenache'],
      soughtProducts: [],
      createdAt: daysAgo(250),
    },
    'e-cantarel': {
      id: 'e-cantarel',
      name: 'Vignobles Cantarel',
      type: 'NEGOCE',
      status: 'VERIFIED',
      region: 'Loire',
      city: 'Sancerre',
      country: 'France',
      appellations: ['Sancerre'],
      grapeVarieties: ['Sauvignon Blanc'],
      soughtProducts: [],
      createdAt: daysAgo(220),
    },
  };

  const users: Record<string, User> = {
    'u-me': {
      id: 'u-me',
      username: 'camille.vasseur',
      email: ME_EMAIL,
      role: 'BOTH',
      firstName: 'Camille',
      lastName: 'Vasseur',
      phone: '+33 6 12 34 56 78',
      entrepriseId: 'e-me',
      entreprise: entreprises['e-me'],
      createdAt: daysAgo(400),
      updatedAt: daysAgo(10),
    },
    'u-hauterive': {
      id: 'u-hauterive',
      username: 'thibault.hauterive',
      email: 'contact@haute-rive.fr',
      role: 'SELLER',
      firstName: 'Thibault',
      lastName: 'Ferrand',
      entrepriseId: 'e-hauterive',
      entreprise: entreprises['e-hauterive'],
    },
    'u-terrasses': {
      id: 'u-terrasses',
      username: 'julie.terrasses',
      email: 'julie@clos-des-terrasses.fr',
      role: 'SELLER',
      firstName: 'Julie',
      lastName: 'Roman',
      entrepriseId: 'e-terrasses',
      entreprise: entreprises['e-terrasses'],
    },
    'u-soleil': {
      id: 'u-soleil',
      username: 'marc.soleil',
      email: 'marc@soleil-levant.fr',
      role: 'SELLER',
      firstName: 'Marc',
      lastName: 'Bousquet',
      entrepriseId: 'e-soleil',
      entreprise: entreprises['e-soleil'],
    },
    'u-cantarel': {
      id: 'u-cantarel',
      username: 'sophie.cantarel',
      email: 'sophie@cantarel.fr',
      role: 'SELLER',
      firstName: 'Sophie',
      lastName: 'Cantarel',
      entrepriseId: 'e-cantarel',
      entreprise: entreprises['e-cantarel'],
    },
    'u-buyer-hugo': {
      id: 'u-buyer-hugo',
      username: 'hugo.lambert',
      email: 'hugo.lambert@negoce-lambert.fr',
      role: 'BUYER',
      firstName: 'Hugo',
      lastName: 'Lambert',
    },
  };

  const annonces: Record<string, Annonce> = {
    'a-chardonnay': {
      id: 'a-chardonnay',
      title: 'Chardonnay — lot de raisins AOP Meursault',
      productType: 'Raisin',
      description:
        'Lot de raisins Chardonnay issus de parcelles en coteaux, conduite en agriculture raisonnée, vendange manuelle.',
      price: 1800,
      volume: 60,
      volumeUnit: 'hl',
      vintage: 2023,
      location: 'Meursault',
      city: 'Meursault',
      region: 'Bourgogne',
      country: 'France',
      availabilityTiming: 'Immédiate',
      certifications: ['HVE'],
      images: [asset('chardonnay-1.jpg'), asset('chardonnay-2.jpg')],
      status: 'PUBLISHED',
      restrictToVerified: false,
      creatorUserId: 'u-me',
      entrepriseId: 'e-me',
      entreprise: entreprises['e-me'],
      creator: { id: 'u-me', username: 'camille.vasseur', firstName: 'Camille', lastName: 'Vasseur' },
      orders: [],
      documents: [],
      _count: { orders: 0 },
      createdAt: daysAgo(18),
      updatedAt: daysAgo(3),
    },
    'a-pinotnoir': {
      id: 'a-pinotnoir',
      title: 'Pinot Noir — lot de raisins AOP Pommard',
      productType: 'Raisin',
      description: 'Petits rendements, belle maturité phénolique, idéal pour vinification en rouge de garde.',
      price: 2400,
      volume: 35,
      volumeUnit: 'hl',
      vintage: 2023,
      location: 'Pommard',
      city: 'Pommard',
      region: 'Bourgogne',
      country: 'France',
      availabilityTiming: 'Sous 2 semaines',
      certifications: ['Bio'],
      images: [asset('pinotnoir-1.jpg'), asset('pinotnoir-2.jpg')],
      status: 'PUBLISHED',
      restrictToVerified: true,
      creatorUserId: 'u-me',
      entrepriseId: 'e-me',
      entreprise: entreprises['e-me'],
      creator: { id: 'u-me', username: 'camille.vasseur', firstName: 'Camille', lastName: 'Vasseur' },
      orders: [],
      documents: [],
      _count: { orders: 0 },
      createdAt: daysAgo(12),
      updatedAt: daysAgo(2),
    },
    'a-merlot': {
      id: 'a-merlot',
      title: 'Merlot — lot de raisins AOP Saint-Émilion',
      productType: 'Raisin',
      description: 'Merlot de coteaux argilo-calcaires, bon état sanitaire, disponible immédiatement.',
      price: 1500,
      volume: 80,
      volumeUnit: 'hl',
      vintage: 2023,
      location: 'Saint-Émilion',
      city: 'Saint-Émilion',
      region: 'Bordeaux',
      country: 'France',
      availabilityTiming: 'Immédiate',
      certifications: ['AOP'],
      images: [asset('merlot-1.jpg'), asset('merlot-2.jpg')],
      status: 'PUBLISHED',
      restrictToVerified: false,
      creatorUserId: 'u-hauterive',
      entrepriseId: 'e-hauterive',
      entreprise: entreprises['e-hauterive'],
      creator: { id: 'u-hauterive', username: 'thibault.hauterive', firstName: 'Thibault', lastName: 'Ferrand' },
      orders: [
        {
          id: 'o-merlot-paid',
          status: 'PAID',
          quantity: 1,
          totalAmount: 150000,
          createdAt: daysAgo(6),
          buyerUserId: 'u-me',
          buyer: { id: 'u-me', username: 'camille.vasseur' },
        },
      ],
      documents: [],
      _count: { orders: 1 },
      purchaseStatus: 'PAID',
      soldOut: true,
      createdAt: daysAgo(40),
      updatedAt: daysAgo(6),
    },
    'a-sauvignon': {
      id: 'a-sauvignon',
      title: 'Sauvignon Blanc — lot de raisins AOP Sancerre',
      productType: 'Raisin',
      description: 'Sauvignon sur sols de silex, profil aromatique intense, vendange mécanique possible.',
      price: 1200,
      volume: 50,
      volumeUnit: 'hl',
      vintage: 2023,
      location: 'Sancerre',
      city: 'Sancerre',
      region: 'Loire',
      country: 'France',
      availabilityTiming: 'Sous 1 mois',
      certifications: [],
      images: [asset('sauvignon-1.jpg'), asset('sauvignon-2.jpg')],
      status: 'PUBLISHED',
      restrictToVerified: false,
      creatorUserId: 'u-cantarel',
      entrepriseId: 'e-cantarel',
      entreprise: entreprises['e-cantarel'],
      creator: { id: 'u-cantarel', username: 'sophie.cantarel', firstName: 'Sophie', lastName: 'Cantarel' },
      orders: [],
      documents: [],
      _count: { orders: 0 },
      createdAt: daysAgo(25),
      updatedAt: daysAgo(5),
    },
    'a-syrah': {
      id: 'a-syrah',
      title: 'Syrah — lot de raisins AOP Crozes-Hermitage',
      productType: 'Raisin',
      description: 'Syrah de coteaux granitiques, faible rendement, forte concentration.',
      price: 1700,
      volume: 40,
      volumeUnit: 'hl',
      vintage: 2023,
      location: 'Tain-l’Hermitage',
      city: 'Tain-l’Hermitage',
      region: 'Rhône',
      country: 'France',
      availabilityTiming: 'Immédiate',
      certifications: ['Terra Vitis'],
      images: [asset('syrah-1.jpg'), asset('syrah-2.jpg')],
      status: 'PUBLISHED',
      restrictToVerified: false,
      creatorUserId: 'u-terrasses',
      entrepriseId: 'e-terrasses',
      entreprise: entreprises['e-terrasses'],
      creator: { id: 'u-terrasses', username: 'julie.terrasses', firstName: 'Julie', lastName: 'Roman' },
      orders: [
        {
          id: 'o-syrah-pending',
          status: 'PENDING',
          quantity: 1,
          totalAmount: 170000,
          createdAt: daysAgo(1),
          buyerUserId: 'u-me',
          buyer: { id: 'u-me', username: 'camille.vasseur' },
        },
      ],
      documents: [],
      _count: { orders: 1 },
      purchaseStatus: 'IN_PROGRESS',
      pendingPurchase: true,
      createdAt: daysAgo(15),
      updatedAt: daysAgo(1),
    },
    'a-grenache': {
      id: 'a-grenache',
      title: 'Grenache — lot de raisins Côtes du Rhône Villages',
      productType: 'Raisin',
      description: 'Vieilles vignes de Grenache, faible rendement, bon potentiel d’extraction.',
      price: 1300,
      volume: 55,
      volumeUnit: 'hl',
      vintage: 2023,
      location: 'Gigondas',
      city: 'Gigondas',
      region: 'Languedoc-Roussillon',
      country: 'France',
      availabilityTiming: 'Sous 2 semaines',
      certifications: ['Bio'],
      images: [asset('grenache-1.jpg'), asset('grenache-2.jpg')],
      status: 'PUBLISHED',
      restrictToVerified: false,
      creatorUserId: 'u-soleil',
      entrepriseId: 'e-soleil',
      entreprise: entreprises['e-soleil'],
      creator: { id: 'u-soleil', username: 'marc.soleil', firstName: 'Marc', lastName: 'Bousquet' },
      orders: [],
      documents: [],
      _count: { orders: 0 },
      createdAt: daysAgo(20),
      updatedAt: daysAgo(4),
    },
  };

  const orders: Record<string, Order> = {
    'o-merlot-paid': {
      id: 'o-merlot-paid',
      quantity: 1,
      unitPrice: 150000,
      totalAmount: 150000,
      currency: 'eur',
      status: 'PAID',
      annonceId: 'a-merlot',
      buyerUserId: 'u-me',
      annonce: {
        id: 'a-merlot',
        title: annonces['a-merlot'].title,
        images: annonces['a-merlot'].images,
        creatorUserId: 'u-hauterive',
        price: 1500,
        volume: 80,
        volumeUnit: 'hl',
        location: 'Saint-Émilion',
        city: 'Saint-Émilion',
        region: 'Bordeaux',
        productType: 'Raisin',
        status: 'PUBLISHED',
        entreprise: { id: 'e-hauterive', name: 'Château Haute-Rive' },
      },
      buyer: { id: 'u-me', username: 'camille.vasseur' },
      payment: {
        id: 'p-merlot',
        stripePaymentId: 'pi_demo_merlot',
        amount: 150000,
        currency: 'eur',
        status: 'SUCCEEDED',
        createdAt: daysAgo(6),
      },
      createdAt: daysAgo(6),
      updatedAt: daysAgo(6),
    },
    'o-syrah-pending': {
      id: 'o-syrah-pending',
      quantity: 1,
      unitPrice: 170000,
      totalAmount: 170000,
      currency: 'eur',
      status: 'PENDING',
      annonceId: 'a-syrah',
      buyerUserId: 'u-me',
      annonce: {
        id: 'a-syrah',
        title: annonces['a-syrah'].title,
        images: annonces['a-syrah'].images,
        creatorUserId: 'u-terrasses',
        price: 1700,
        volume: 40,
        volumeUnit: 'hl',
        location: 'Tain-l’Hermitage',
        city: 'Tain-l’Hermitage',
        region: 'Rhône',
        productType: 'Raisin',
        status: 'PUBLISHED',
        entreprise: { id: 'e-terrasses', name: 'Clos des Terrasses' },
      },
      buyer: { id: 'u-me', username: 'camille.vasseur' },
      payment: null,
      createdAt: daysAgo(1),
      updatedAt: daysAgo(1),
    },
  };

  const conversations: Record<string, Conversation> = {
    'c-merlot': {
      id: 'c-merlot',
      annonceId: 'a-merlot',
      buyerId: 'u-me',
      isSAV: false,
      annonce: {
        id: 'a-merlot',
        title: annonces['a-merlot'].title,
        entrepriseId: 'e-hauterive',
        creatorUserId: 'u-hauterive',
        images: annonces['a-merlot'].images,
        price: 1500,
        creator: { id: 'u-hauterive', username: 'thibault.hauterive', firstName: 'Thibault', lastName: 'Ferrand' },
      },
      buyer: { id: 'u-me', username: 'camille.vasseur', firstName: 'Camille', lastName: 'Vasseur' },
      messages: [
        {
          id: 'm-merlot-1',
          content: 'Bonjour, le lot de Merlot est-il toujours disponible en totalité ?',
          senderId: 'u-me',
          sender: { id: 'u-me', username: 'camille.vasseur' },
          conversationId: 'c-merlot',
          createdAt: daysAgo(7),
        },
        {
          id: 'm-merlot-2',
          content: 'Bonjour Camille, oui le lot complet est disponible, vendange prévue la semaine prochaine.',
          senderId: 'u-hauterive',
          sender: { id: 'u-hauterive', username: 'thibault.hauterive' },
          conversationId: 'c-merlot',
          createdAt: daysAgo(7),
        },
        {
          id: 'm-merlot-3',
          content: 'Parfait, je passe commande dès maintenant.',
          senderId: 'u-me',
          sender: { id: 'u-me', username: 'camille.vasseur' },
          conversationId: 'c-merlot',
          createdAt: daysAgo(6),
        },
      ],
      createdAt: daysAgo(7),
      updatedAt: daysAgo(6),
    },
    'c-syrah': {
      id: 'c-syrah',
      annonceId: 'a-syrah',
      buyerId: 'u-me',
      isSAV: false,
      annonce: {
        id: 'a-syrah',
        title: annonces['a-syrah'].title,
        entrepriseId: 'e-terrasses',
        creatorUserId: 'u-terrasses',
        images: annonces['a-syrah'].images,
        price: 1700,
        creator: { id: 'u-terrasses', username: 'julie.terrasses', firstName: 'Julie', lastName: 'Roman' },
      },
      buyer: { id: 'u-me', username: 'camille.vasseur', firstName: 'Camille', lastName: 'Vasseur' },
      messages: [
        {
          id: 'm-syrah-1',
          content: 'Bonjour, je viens de lancer le paiement pour le lot de Syrah.',
          senderId: 'u-me',
          sender: { id: 'u-me', username: 'camille.vasseur' },
          conversationId: 'c-syrah',
          createdAt: daysAgo(1),
        },
        {
          id: 'm-syrah-2',
          content: 'Bien reçu, je vous confirme dès validation bancaire.',
          senderId: 'u-terrasses',
          sender: { id: 'u-terrasses', username: 'julie.terrasses' },
          conversationId: 'c-syrah',
          createdAt: daysAgo(1),
        },
      ],
      createdAt: daysAgo(1),
      updatedAt: daysAgo(1),
    },
    'c-chardonnay-incoming': {
      id: 'c-chardonnay-incoming',
      annonceId: 'a-chardonnay',
      buyerId: 'u-buyer-hugo',
      isSAV: false,
      annonce: {
        id: 'a-chardonnay',
        title: annonces['a-chardonnay'].title,
        entrepriseId: 'e-me',
        creatorUserId: 'u-me',
        images: annonces['a-chardonnay'].images,
        price: 1800,
        creator: { id: 'u-me', username: 'camille.vasseur', firstName: 'Camille', lastName: 'Vasseur' },
      },
      buyer: { id: 'u-buyer-hugo', username: 'hugo.lambert', firstName: 'Hugo', lastName: 'Lambert' },
      messages: [
        {
          id: 'm-chard-1',
          content: 'Bonjour, votre lot de Chardonnay m’intéresse. Est-il négociable sur le volume ?',
          senderId: 'u-buyer-hugo',
          sender: { id: 'u-buyer-hugo', username: 'hugo.lambert' },
          conversationId: 'c-chardonnay-incoming',
          createdAt: daysAgo(2),
        },
      ],
      createdAt: daysAgo(2),
      updatedAt: daysAgo(2),
    },
  };

  const documents: Record<string, DocumentItem> = {
    'd-kbis': {
      id: 'd-kbis',
      url: asset('chardonnay-1.jpg'),
      type: 'KBIS',
      status: 'APPROVED',
      visibility: 'PUBLIC',
      originalName: 'kbis-domaine-trois-chenes.pdf',
      label: 'Extrait KBIS',
      createdAt: daysAgo(100),
    },
    'd-vat': {
      id: 'd-vat',
      url: asset('chardonnay-2.jpg'),
      type: 'VAT_CERTIFICATE',
      status: 'APPROVED',
      visibility: 'PUBLIC',
      originalName: 'attestation-tva.pdf',
      label: 'Attestation TVA',
      createdAt: daysAgo(100),
    },
  };

  return {
    loggedIn: false,
    currentUserId: null,
    users,
    entreprises,
    annonces,
    orders,
    conversations,
    documents,
  };
}
